config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  # https://railsguides.jp/routing.html#「浅い」ネスト
  resources :users do
    resources :foods, only: [:index, :new, :search]
  end
  resources :foods, only: [:create, :edit, :update, :destroy, :search]
  get '/foods/search', to: 'foods#search'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, :kind_id, presence: true
  before_save :update_nutri
  after_save :delete_lte_zero

  private
  def update_nutri
    if self.amount.nil?
      self.amount = 0
    end
    kind = FoodKind.find(self.kind_id)
    self.protein = kind.protein * self.amount
    self.lipd = kind.lipd * self.amount
    self.carbon = kind.carbon * self.amount
    self.vitamin = kind.vitamin * self.amount
    self.minerals = kind.minerals * self.amount
  end

  def delete_lte_zero
    if self.amount <= 0
      #self = Food.find(params[:id]).destroy
      self.destroy
    end
  end
end

app/models/food_kind.rb
class FoodKind < ApplicationRecord
  def short_name
    foodname = self.kindname
    if foodname =~ /（.*）/
      foodname.gsub!(/（.*）/, "")
    end
    if
      foodname =~ /＜.*＞/
      foodname.gsub!(/＜.*＞/, "")
    end
    if foodname =~ /［.*］/
      foodname.gsub!(/［.*］/, "")
    end
    if foodname =~ /^　.*/
      foodname.gsub!(/^　*/, "")
    end
    return foodname
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :foods, dependent: :destroy
  before_save { email.downcase! }
  has_secure_password
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 4, maximum: 255 }

  def nutri_stats
    # 栄養素/日分
    {
      protein:  foods.sum(:protein) / 60, 
      lipd:     foods.sum(:lipd) / 70, 
      carbon:   foods.sum(:carbon) / 400, 
      vitamin:  foods.sum(:vitamin) / 130, 
      minerals: foods.sum(:minerals) / 5600, 
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController

  def index
    @user = User.find(params[:user_id])
    @foods = @user.foods.all
  end

  def search
    @kinds = FoodKind.where('name LIKE(?) ', "%#{params[:keyword].tr('ア-ン', 'あ-ん')}%").limit(20)
    #respond_to do |format|
    #  format.json { render 'index', json: @users }
    #end
    render json: @kinds
  end

  def new
    @user = User.find(params[:user_id])
    @food = Food.new
  end

  def create
    @user = User.find(params[:user_id])
    @food = @user.foods.build(food_params)
    if @food.save
      redirect_to user_foods_path(@user)
    else
      redirect_back(fallback_location: user_foods_path(@user))
    end
  end

  def edit
    @food = Food.find(params[:id])
    @user = User.find(@food.user_id)
  end

  def update
    @food = Food.find(params[:id])
    if @food.update_attributes(food_params)
      redirect_to user_foods_path(@food.user_id)
    else
      redirect_to root_url
    end
  end

  def destroy
    @food = Food.find(params[:id]).destroy
    #redirect_back(fallback_location: root_url)
    redirect_to user_foods_path(@food.user_id)
  end

  private
    def food_params
      params.require(:food).permit(:foodname, :kind_id, :amount)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:dange] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :correct_user, only: [:show, :edit, :update, :destroy]
  #before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
    @foods = @user.foods.paginate(page: params[:page])
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end

    def correct_user
      @user = User.find(params[:id])
      unless current_user?(@user)
        flash[:danger] = 'Action not permitted'
        redirect_to login_path
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def current_user?(user)
    user == current_user
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/_food.html.erb
<div class="food-block" id="food-<%= food.id %>">
  <%= link_to(edit_food_path(food)) do %>
    <div class="flex-column flex-align-center">
    <div class="flex-column">
      <div class="flex-row flex-justify-start">
        <span class="food-tag food-date"><%= food.created_at.strftime("%m/%d")%></span>
      </div>

      <%= image_tag('food_kinds/%04d.jpg' % food.kind_id, class: "food-img") %>

      <div class="flex-row flex-justify-end">
        <span class="food-tag food-amount">×<%= food.amount %></span>
      </div>
    </div>
    <span class=""><small><%= truncate(food.foodname, length: 6, omission: "…") %></small></span>
    </div>
  <% end %>
</div>

app/views/foods/edit.html.erb
<div class="container flex-fixed">
  <h1><%= @user.name %>の冷蔵庫</h1>

  <h3>食品を取り出す</h3>
</div>

<div class="container flex-content-scroll">
  <div class="card-s bg-c-3">
    <span><%= @food.foodname %></span>
    <%= image_tag('food_kinds/%04d.jpg' % @food.kind_id, class: "food-img") %>

    <span>入れた日時: <%= @food.created_at.strftime("%m月%d日%H時")%></span>
  </div>

  <%= form_for(@food) do |f| %>
    <%= f.label :amount, "取出し後の数量(100g)" %>
    <%= f.text_field :amount, placeholder: @food.amount, class: "form-control" %>

    <%= link_to '全て取出す', @food, method: :delete, class: "btn btn-primary" %>

    <%= f.submit "送信", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/foods/index.html.erb
<div class="container flex-fixed flex-row flex-justify-between">
  <h1><%= @user.name %>の冷蔵庫</h1>
  <h3>Foods (<%= @user.foods.count %>)</h3>
</div>

<div id="foods-feed" class="flex-content-scroll bg-c-3 card-m">
  <div class="flex-row flex-wrap flex-justify-around pd-8">
    <%= render @foods %>
  </div>
</div>

app/views/foods/new.html.erb
<div class="container flex-fixed">
  <h1><%= @user.name %>の冷蔵庫</h1>
  <h3>食べ物を入れる</h3>
</div>

<!-- form -->
<%= form_for(@food, html: {class: "container flex-content-scroll"}) do |f| %>
  <%= hidden_field_tag :user_id, @user.id %>
  <!-- error message -->

  <!-- Ajax -->
  <%= f.label :foodname, "食品名" %>
  <%= f.text_field :foodname, class: 'form-control', id: "search-form" %>

  <label for="result">食品種類（食品名の検索結果を選択）</label>
  <div id="result" class="flex-content-strech card-m bg-c-3">
  </div>

  <!-- amount -->
  <%= f.label :amount, "数量(100g)" %>
  <%= f.text_field :amount, class: 'form-control' %>

  <%= f.submit '冷蔵庫に入れる', class: 'btn btn-primary' %>
<% end %>

<!-- Ajax Script at foods-search.js -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://ajax.googleapis.com/ajax/libs/jquery/2.0.0/jquery.min.js" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://www.gstatic.com/charts/loader.js" %>
  </head>

  <body>
    <div id="wrapper-container" class="flex-column bg-white">

      <!-- Header -->
      <div id="header" class="flex-row flex-justify-between flex-align-center bg-c-1 fg-white">
        <div name="left menu" id="menu-left" class="flex-row">
          <%= link_to 'VRefrige', root_path %>
        </div>
        <div name="right menu" id="menu-right" class="flex-row">
          <% if logged_in? %>
            <%= link_to current_user.name, edit_user_path(current_user) %>
            <%= link_to image_tag('icons/logout.svg', class: "header-icon-btn", id: "icon-logout"), logout_path, method: 'delete' %>
          <% else %>
            <%= link_to 'ログイン', login_path %>
          <% end %>
        </div>
      </div>

      <!-- Flash -->
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>

      <!-- Main Content -->
      <div id="main" class="flex-content-strech flex-column bg-white card-l">
        <%= yield %>
      </div>

      <!-- Footer -->
      <div id="footer" class="flex-row flex-justify-around flex-align-center bg-white">
        <% if logged_in? %>
          <%= link_to image_tag("icons/foods#{current_page?(user_foods_path(current_user)) ? '-on' : ''}.svg", class: "footer-icon-btn", id: "icon-foods"), user_foods_path(current_user) %>
          <%= link_to image_tag("icons/plus#{current_page?(new_user_food_path(current_user)) ? '-on' : ''}.svg", class: "footer-icon-btn", id: "icon-plus"), new_user_food_path(current_user) %>
          <%= link_to image_tag("icons/stats#{current_page?(user_path(current_user)) ? '-on' : ''}.svg", class: "footer-icon-btn", id: "icon-stats"), user_path(current_user) %>
        <% else %>
          <%= link_to 'Created by tema 冷蔵庫', about_path %>
        <% end %>
      </div>

    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<div class="container">
  <h1>メンバー</h1>
  <ul>
    <li>潘秋実 (<%= link_to 'link', 'https://www.gitshell.net' %>)</li>
    <li>小平舞</li>
    <li>山﨑睦月</li>
    <li>佐藤千尋</li>
  </ul>
</div>

app/views/static_pages/home.html.erb
<div class="container flex-fixed">
  <h1>Virtual Refrigerator</h1>

  <% if logged_in? %>
    <%= current_user.name %>としてログイン中
  <% else %>
    <%= link_to '新規登録', signup_path, class: "btn btn-primary" %>
    <%= link_to 'ログイン', login_path, class: "btn btn-primary" %>
  <% end %>
</div>

<div class="container flex-content-scroll">
  <p class="card-s bg-c-3">
  ようこそ！!Virtual Refrigeratorへ!
  Virtual Refrigeratorは、あなたのポケットの中に入る冷蔵庫です！いつでもどこでもあなたの冷蔵庫の中身が確認できます。そして冷蔵庫の中の栄養素を教えます

  使い方は簡単で
  １. 冷蔵庫に入っているものを登録
  2.  使ったら削除
  </p>

  <%#= image_tag 'open_refrige.png', id: "home-img" %>

  <p class="card-s bg-c-3">
  Virtual Refrigeratorの詳しい使い方
  1. [新規登録]ボタンからユーザー登録をします。ユーザー名、当サービス未登録のメールアドレス、新規パスワードを入力します。
  （登録済みの場合は[ログイン]します。この場合、登録済みのメールアドレスとパスワードを入力します。）
  2. ユーザーの冷蔵庫に入っている食べ物の数と五大栄養素の含有値が表示されます。
  3. 画面下部のボタンは以下の機能を使える画面を呼び出します。
  左（カブのマーク）　冷蔵庫に入っている食べ物を表示します。食べ物を選択すると冷蔵庫から出したりさらに追加したりすることができます。
  中央（＋のマーク）　冷蔵庫に食べ物を入れます。食品名フォームに入力すると食べ物の選択肢が表示されるので、その中から入れたい食べ物を選びます。食品名と数量を入力して[冷蔵庫に入れる]ボタンを押すと食べ物を入れられます。
  右（棒グラフのマーク）　冷蔵庫に入っている食べ物の数と五大栄養素の含有値が表示されます。
  4. 画面右上のマークを押すとログアウトできます。ログアウトすると1. の画面に戻ります。
  </p>

  <%= link_to '作成メンバー', about_path %>
  <%= link_to 'Slide', 'https://docs.google.com/presentation/d/e/2PACX-1vSs4rd45vZLkE5Z8QfE_Wn_MFV8ABQM4I-HkJbRul28QhfmiQm1gP4IAKtPJusS8vbZyFw0kV_WU3Eu/pub?start=false&loop=false&delayms=3000' %>
  <%= link_to 'GitHub', 'https://github.com/qiugits/VirtualRefrigerator' %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2>エラー：</h2>
      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.submit '送信', class: "btn btn-primary" %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <h1>Editing User</h1>

  <%= render 'form', user: @user %>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="status">
  <div class="users">
    <h1>Users</h1>

    <table>
      <thead>
        <tr>
          <th>Name</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
          <tr>
            <td><%= user.name %></td>
            <td><%= link_to 'Show', user %></td>
            <td><%= link_to 'Edit', edit_user_path(user) %></td>
            <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  <br>

  <%= link_to 'New User', new_user_path %>
  </div>
</div>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

app/views/users/show.html.erb
<% stats = @user.nutri_stats %>

<div class="container flex-fixed">
  <h1><%= @user.name %>の冷蔵庫</h1>
  <h3>Foods (<%= @user.foods.count %>)</h3>
</div>
<div class="container flex-content-scroll">
  <div class="graph-cont">
    <label for="stats-protein">プロテイン</label>
    <div class="bar" id="stats-protein"><%= "%.1f" % (stats[:protein]) %>日分</div>
    <label for="stats-lipd">脂肪</label>
    <div class="bar" id="stats-lipd"><%= "%.1f" % (stats[:lipd]) %>日分</div>
    <label for="stats-carbon">炭水化物</label>
    <div class="bar" id="stats-carbon"><%= "%.1f" % (stats[:carbon]) %>日分</div>
    <label for="stats-vitamin">ビタミン</label>
    <div class="bar" id="stats-vitamin"><%= "%.1f" % (stats[:vitamin]) %>日分</div>
    <label for="stats-minerals">ミネラル</label>
    <div class="bar" id="stats-minerals"><%= "%.1f" % (stats[:minerals]) %>日分</div>
  </div>
</div>

<style type="text/css">
  #stats-protein:after{
    max-width: <%= [stats[:protein], 7].min / 7 * 100 %>%;
  }
  #stats-lipd:after{
    max-width: <%= [stats[:lipd], 7].min / 7 * 100 %>%;
  }
  #stats-carbon:after{
    max-width: <%= [stats[:carbon], 7].min / 7 * 100 %>%;
  }
  #stats-vitamin:after{
    max-width: <%= [stats[:vitamin], 7].min / 7 * 100 %>%;
  }
  #stats-minerals:after{
    max-width: <%= [stats[:minerals], 7].min / 7 * 100 %>%;
  }
</style>